name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]   # change if your branch is "master" or something else

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload build output
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist   # adjust if your build output folder is "build" instead of "dist"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
